# Generated by Django 6.0.2 on 2026-02-27 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_product_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cost',
        ),
    ]
