# Generated by Django 6.0.2 on 2026-03-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_category_store_store_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
